spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: pg1.vpc.cloudera.com:9092

      bindings:
        output:
          destination: c5
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 4

        person-out:
          destination: c6
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 3

server:
  port: 8080

management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

info:
  app:
    name: kafka multiple partition demo
